CREATE TABLE #EXAMPLE_TABLE
(
    INT_FIELD int,
	STR_FIELD varchar(100),
	DATE_FIELD datetime
)
TRUNCATE TABLE #EXAMPLE_TABLE
SET NOCOUNT ON
DECLARE @i INT = 0
WHILE @i < 10
	  BEGIN
INSERT #EXAMPLE_TABLE(INT_FIELD, STR_FIELD, DATE_FIELD) 
VALUES
(FLOOR(300*RAND()), REPLICATE('s', @i + 1), GETDATE())
SET @i = @i + 1
	END
SELECT * FROM #EXAMPLE_TABLE