CREATE VIEW [Количество_кафедр] WITH SCHEMABINDING
AS SELECT fc.FACULTY_NAME[Факультет], COUNT(*)[Кол-во кафедр]
FROM dbo.FACULTY fc INNER JOIN dbo.PULPIT pp ON fc.FACULTY = pp.FACULTY
GROUP BY fc.FACULTY_NAME