use UNIVER
SELECT FACULTY.FACULTY_NAME, PULPIT.PULPIT, GROUPS.PROFESSION, 
	   SUBJECT.SUBJECT_NAME, STUDENT.NAME, PROGRESS.NOTE, 
CASE
	WHEN (PROGRESS.NOTE = 6) THEN 'шесть'
	WHEN (PROGRESS.NOTE = 7) THEN 'семь'
	WHEN (PROGRESS.NOTE = 8) THEN 'восемь'
	ELSE 'ниже 6'
END [ќценки]
FROM PROGRESS 
			  INNER JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT
			  INNER JOIN PULPIT ON PULPIT.PULPIT = SUBJECT.PULPIT
			  INNER JOIN FACULTY ON FACULTY.FACULTY = PULPIT.FACULTY
			  INNER JOIN STUDENT ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
			  INNER JOIN GROUPS ON GROUPS.IDGROUP = STUDENT.IDGROUP
WHERE PROGRESS.NOTE BETWEEN 6 AND 8 ORDER BY PROGRESS.NOTE DESC		  
			 