USE UNIVER

SELECT DISTINCT PULPIT.PULPIT_NAME
FROM PULPIT, FACULTY, PROFESSION
WHERE PULPIT.FACULTY = FACULTY.FACULTY
AND FACULTY.FACULTY IN (SELECT PROFESSION.FACULTY FROM PROFESSION 
						WHERE PROFESSION.PROFESSION_NAME LIKE '%технология%' OR PROFESSION.PROFESSION_NAME LIKE '%технологии%')