USE UNIVER

SELECT AUDITORIUM, AUDITORIUM_CAPACITY, AUDITORIUM_TYPE
FROM AUDITORIUM audit1
WHERE AUDITORIUM_CAPACITY = (SELECT TOP(1) AUDITORIUM_CAPACITY 
							 FROM AUDITORIUM audit2 
							 WHERE audit2.AUDITORIUM_TYPE = audit1.AUDITORIUM_TYPE
							 ORDER BY AUDITORIUM_CAPACITY DESC)