USE UNIVER

SELECT FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT,
ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))), 2)[AVG_NOTE]
FROM FACULTY INNER JOIN GROUPS ON FACULTY.FACULTY = GROUPS.FACULTY
			 INNER JOIN STUDENT ON STUDENT.IDGROUP = GROUPS.IDGROUP
			 INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
			 WHERE GROUPS.FACULTY = 'ÒÎÂ'
GROUP BY FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT