USE UNIVER

SELECT SUBJECT, (SELECT COUNT(*) FROM PROGRESS p2 WHERE p1.SUBJECT = p2.SUBJECT 
AND p1.NOTE = p2.NOTE)[COUNT_OF_STUDENTS]
FROM PROGRESS p1
GROUP BY SUBJECT, NOTE
HAVING p1.NOTE BETWEEN 8 AND 9
ORDER BY COUNT_OF_STUDENTS DESC