USE UNIVER

SELECT PROGRESS.SUBJECT, FACULTY.FACULTY_NAME, GROUPS.PROFESSION, (2014 - GROUPS.YEAR_FIRST)[COURSE],
ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))), 2)[AVG_NOTE]
FROM FACULTY INNER JOIN GROUPS ON FACULTY.FACULTY = GROUPS.FACULTY
			 INNER JOIN STUDENT ON STUDENT.IDGROUP = GROUPS.IDGROUP
			 INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
WHERE(PROGRESS.SUBJECT = 'Œ¿Ëœ' OR PROGRESS.SUBJECT = '¡ƒ')
GROUP BY PROGRESS.SUBJECT, GROUPS.YEAR_FIRST, GROUPS.PROFESSION, FACULTY.FACULTY_NAME
ORDER BY AVG_NOTE DESC